name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.123.7'
          extended: true

      # 1. 建置 Hugo 網站
      - name: Build site
        run: hugo --minify --gc

      # 2. 直接使用 npx 執行 Pagefind 來建立索引
      #    這會繞過有問題的 GitHub Action
      - name: Build Pagefind search index
        run: npx --yes pagefind --site public --bundle-dir pagefind

      # 3. 檢查連結
      - name: Check links
        uses: wjdp/htmltest-action@master
        with:
          path: ./public
          config: .htmltest.yml
          
      # 4. 部署
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
