name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.123.7'
          extended: true

      # ↓↓↓ 新增的診斷步驟 ↓↓↓
      - name: List project files for debugging
        run: |
          echo "--- Root directory ---"
          ls -l
          echo "--- layouts/_default directory ---"
          ls -l layouts/_default

      # 原有的建置步驟
      - name: Build site
        run: hugo --minify --gc

      - name: Check links
        uses: wjdp/htmltest-action@master
        with:
          path: ./public
          config: .htmltest.yml
          
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
