name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.123.7'
          extended: true

      - name: Build site
        run: hugo --minify --gc

      # 新增 Pagefind 建立索引的步驟
      - name: Run Pagefind Indexing
        uses: cloudcannon/pagefind-action@v1

      - name: Check links
        uses: wjdp/htmltest-action@master
        with:
          path: ./public
          config: .htmltest.yml
          
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
